@NasaApiKey = DEMO_KEY
@StartDate = 2026-07-13
@EndDate = 2026-07-16

GET https://api.nasa.gov/neo/rest/v1/feed?start_date={{StartDate}}&end_date={{EndDate}}&api_key={{NasaApiKey}}
Accept: application/json

###
