// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeoWatcher.Migrations
{
    [DbContext(typeof(NeoContext))]
    [Migration("20260919183051_AddCloseApproachDateIndexBack")]
    partial class AddCloseApproachDateIndexBack
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeoWatcher.Models.Asteroid", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("EstimatedDiameterMax")
                        .HasColumnType("double precision");

                    b.Property<double>("EstimatedDiameterMin")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsPotentiallyHazardous")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Asteroids");
                });

            modelBuilder.Entity("NeoWatcher.Models.CloseApproach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AsteroidId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CloseApproachDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MissDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<double>("RelativeVelocityKmh")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CloseApproachDate");

                    b.HasIndex("AsteroidId", "CloseApproachDate")
                        .IsUnique();

                    b.ToTable("CloseApproaches");
                });

            modelBuilder.Entity("NeoWatcher.Models.CloseApproach", b =>
                {
                    b.HasOne("NeoWatcher.Models.Asteroid", "Asteroid")
                        .WithMany("CloseApproaches")
                        .HasForeignKey("AsteroidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asteroid");
                });

            modelBuilder.Entity("NeoWatcher.Models.Asteroid", b =>
                {
                    b.Navigation("CloseApproaches");
                });
#pragma warning restore 612, 618
        }
    }
}
