// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeoWatcher.Migrations
{
    [DbContext(typeof(NeoContext))]
    [Migration("20260716074610_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NearEarthObject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CloseApproachDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EstimatedDiameterMax")
                        .HasColumnType("double precision");

                    b.Property<double>("EstimatedDiameterMin")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsPotentiallyHazardous")
                        .HasColumnType("boolean");

                    b.Property<double>("MissDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RelativeVelocityKmh")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("NearEarthObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
